services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace
      - party-reg-node-modules:/workspace/frontend/node_modules
      - party-reg-pre-commit-cache:/home/vscode/.cache/pre-commit

  db:
    image: mcr.microsoft.com/mssql/server:2022-CU14-ubuntu-22.04
    platform: linux/amd64
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - party-reg-mssql:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 2G

  saml-idp:
    image: kristophjunge/test-saml-idp
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SIMPLESAMLPHP_SP_ENTITY_ID=next-auth-client
      - SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE=http://localhost:3000/api/auth/login/saml

volumes:
  party-reg-mssql:
  party-reg-node-modules:
  party-reg-pre-commit-cache:
